from aiogram.fsm.state import State, StatesGroup

class WalletStates(StatesGroup):
    waiting_amount = State()
    waiting_receipt = State()

class TicketStates(StatesGroup):
    waiting_subject = State()
    waiting_message = State()
    waiting_reply = State()

class OwnerStates(StatesGroup):
    waiting_brand_name = State()
    waiting_welcome_text = State()
    waiting_about_text = State()
    waiting_rules_text = State()
    waiting_support_text = State()
    waiting_signature = State()
    waiting_logo = State()
    waiting_card_number = State()
    waiting_card_holder = State()
    waiting_receipt_channel = State()
    waiting_support_group = State()
    waiting_min_charge = State()
    waiting_max_charge = State()
    waiting_referral_percent = State()
    waiting_trial_days = State()
    waiting_trial_gb = State()
    waiting_broadcast = State()
    waiting_forced_channel = State()
    waiting_admin_id = State()
    waiting_admin_permissions = State()
    waiting_panel_name = State()
    waiting_panel_type = State()
    waiting_panel_url = State()
    waiting_panel_username = State()
    waiting_panel_password = State()
    waiting_panel_inbound = State()
    waiting_panel_subdomain = State()
    waiting_plan_name = State()
    waiting_plan_panel = State()
    waiting_plan_days = State()
    waiting_plan_gb = State()
    waiting_plan_price = State()
    waiting_discount_code = State()
    waiting_discount_percent = State()
    waiting_discount_uses = State()
    waiting_restore_file = State()

class AdminStates(StatesGroup):
    waiting_user_search = State()
    waiting_charge_user_id = State()
    waiting_charge_amount = State()
    waiting_reject_reason = State()